api_keys: {}
auth:
  secret_key: your-secure-secret-key-here
cody:
  api_token: sgp_fd1b4edb60bf82b8_25160fe1b70894533a193b9e3ff79f3aa2058454
  endpoint: https://sourcegraph.com/.api/graphql
database:
  host: localhost
  password: ''
  username: ''
tokens: {}
