# AI Configuration
ai:
  cohere:
    api_key: "Iit61crv19hvn8saKns5mWdqVin2ExICRufkO67v"
    model: "command"
  local:
    mistral:
      enabled: true
      path: "models/mistral-7b.gguf"
    deepseek:
      enabled: true
      path: "models/deepseek-coder-1.3b"
