ai:
  cody:
    connection_state: inactive
    enabled: true
    mode: active
    priority_tasks:
    - defi
    - dao
    - governance
    status: active
    timeout: 30
  llama:
    enabled: true
    models:
      fallback:
        context_size: 8192
        enabled: true
        max_tokens: 2048
        name: deepseek-V3-api
        temperature: 0.7
        type: api
      primary:
        context_size: 16384
        enabled: true
        max_tokens: 2048
        name: deepseek-coder:1.3b
        temperature: 0.7
        type: local
app:
  environment: development
  name: automation_tool
  version: 1.0.0
logging:
  level: INFO
  retention_days: 30
templates:
  path: config/templates
  supported_types:
  - python
  - rust
  - solidity
  - web3
  - react
  - nodejs
